import type { Civilization, Culture, EventCategory, GreatPerson, HistoryEvent, MapSize, PersonRole, Province, Rank, Religion, RulerRecord, Terrain, WorldConfig, WorldState } from './types';
const COLORS=['#cf6b4f','#d3a84c','#6da86b','#4f90b8','#8a72c8','#c45f89','#6cb7ad','#c9874a','#7c9b52','#aa665c','#6f83c2','#b497d6','#be7a9d','#4fa3a5','#d47b56','#9ca34f','#748cbe','#b96d78','#689e7f','#9a7db7','#d19a52','#67a6b0','#8b9f64','#be6a5a','#7d79b8','#ca8461','#5c9b8c','#a98a54','#758fc0','#b06c96'];
const ROOTS=['Amara','Achaean','Aksum','Alani','Andari','Arveni','Aureli','Bactri','Beran','Carthi','Celtai','Dacari','Etruri','Franci','Garam','Helveni','Iberi','Illyri','Kushai','Lusani','Mauri','Nabari','Numari','Ostari','Phoeni','Sabari','Sarmati','Thracai','Umbri','Vandari','Veneti','Yamari','Zagri'];
const HISTORIC=['Athens','Sparta','Rome','Carthage','Byzantium','Macedon','Persia','Babylon','Assyria','Numidia','Iberia','Armenia','Arabia','Scythia','Etruria','Phoenicia','Kush','Aksum','Mali','Songhai','Rus','Siam'];
const FIRST=['Cassian','Elira','Marcus','Loran','Aurelia','Tavian','Neris','Ilyan','Seraph','Mara','Oren','Valeria','Darius','Kael','Sorin','Lysandra','Theon','Mira','Edrin','Sabine'];
const TRAITS=['Ambitious','Charismatic','Cruel','Genius','Diplomatic','Zealous','Bold','Patient','Builder','Reformer','Cautious','Visionary'];
const ROLES:PersonRole[]=['Scientist','Engineer','Merchant','Religious Figure','General','Artist'];
const RANKS:Rank[]=['Tribe','Settlement','City-State','Duchy','Kingdom','Empire'];
class RNG{constructor(public seed:number){}next(){this.seed=(this.seed*1664525+1013904223)>>>0;return this.seed/4294967296}int(a:number,b:number){return Math.floor(this.next()*(b-a+1))+a}pick<T>(a:T[]){return a[this.int(0,a.length-1)]}chance(p:number){return this.next()<p}}
export const displayYear=(y:number)=>y<0?`${Math.abs(y)} BCE`:`${y} CE`;
export const eraName=(y:number)=>y<-1800?'Age of Tribes':y<-700?'Bronze Age':y<500?'Classical Age':y<1400?'Medieval Age':y<1750?'Age of Discovery':y<1950?'Industrial Age':'Modern Age';
export const rankWeight=(r:Rank)=>RANKS.indexOf(r)+1;
const dims=(s:MapSize)=>s==='small'?{w:12,h:10}:s==='medium'?{w:18,h:14}:{w:25,h:18};
const rootName=(n:string)=>n.replace(/\s+(Tribe|Settlement|League|Duchy|Kingdom|Empire)$/i,'').replace(/(polis|grad|burg|ium|land)$/i,'');
const adjective=(n:string)=>`${rootName(n).replace(/[^A-Za-z]/g,'')}ian`;
function terrainAt(x:number,y:number,w:number,h:number,variant:number,rng:RNG):Terrain{
  const nx=x/(w-1),ny=y/(h-1); const blobs=variant%3===0?[[.24,.28,.25],[.70,.34,.22],[.53,.76,.18],[.88,.78,.09]]:variant%3===1?[[.18,.54,.27],[.51,.25,.21],[.76,.62,.27],[.50,.86,.10]]:[[.22,.25,.17],[.22,.72,.20],[.58,.48,.27],[.85,.24,.12],[.84,.83,.10]];
  const land=blobs.some(([bx,by,r])=>Math.hypot(nx-bx,ny-by)<r+(rng.next()-.5)*.045);
  if(!land)return'ocean'; const t=rng.next(); if(t<.12)return'mountain';if(t<.30)return'forest';if(t<.40)return'desert';if(t<.46)return'tundra';return'plains';
}
function neighbors(p:Province,all:Province[]){const d=p.y%2===0?[[-1,0],[1,0],[-1,-1],[0,-1],[-1,1],[0,1]]:[[ -1,0],[1,0],[0,-1],[1,-1],[0,1],[1,1]];return d.map(([dx,dy])=>all.find(q=>q.x===p.x+dx&&q.y===p.y+dy)).filter(Boolean) as Province[]}
function addEvent(s:WorldState,cat:EventCategory,title:string,description:string,importance:number,civIds:number[],extra:Partial<HistoryEvent>={}){const e:HistoryEvent={id:s.nextEventId++,year:s.year,category:cat,title,description,importance,civIds,...extra};s.events.unshift(e);civIds.forEach(id=>s.civilizations.find(c=>c.id===id)?.history.unshift(e.id))}
function newRuler(s:WorldState,c:Civilization,rng:RNG):RulerRecord{const r:RulerRecord={id:s.nextRulerId++,name:`${rng.pick(FIRST)} ${rootName(c.originTribe)}`,realmId:c.id,born:s.year-rng.int(20,45),reignStart:s.year,administration:rng.int(10,100),military:rng.int(10,100),diplomacy:rng.int(10,100),trait:rng.pick(TRAITS),startProvinces:c.provinces.length,startTechnology:c.technology,startGDP:c.gdp,startPopulation:c.population,historicalRelevance:1};s.rulers.push(r);c.rulerId=r.id;return r}
function rankFor(c:Civilization):Rank{const p=c.provinces.length;if(p>=18&&c.population>160000)return'Empire';if(p>=10&&c.population>65000)return'Kingdom';if(p>=6)return'Duchy';if(p>=3)return'City-State';if(c.population>1800)return'Settlement';return'Tribe'}
function polityName(c:Civilization,r:Rank,rng:RNG){const root=rootName(c.originTribe);if(r==='Settlement')return`${root}${rng.pick(['polis','ton','grad','burg','haven'])}`;if(r==='City-State')return rng.chance(.55)?rng.pick(HISTORIC):c.capital;if(r==='Duchy')return`Duchy of ${c.capital}`;if(r==='Kingdom')return rng.chance(.5)?`${root}land`:`Kingdom of ${c.capital}`;if(r==='Empire')return`${rng.chance(.35)?rng.pick(HISTORIC):root} Empire`;return`${root} Tribe`}
function spawnPerson(s:WorldState,c:Civilization,rng:RNG,forced?:PersonRole){const role=forced??rng.pick(ROLES),stars=rng.int(1,5) as 1|2|3|4|5;const p:GreatPerson={id:s.nextPersonId++,name:`${rng.pick(FIRST)} ${rootName(c.originTribe)}`,role,born:s.year-rng.int(18,32),realmId:c.id,cultureId:c.cultureId,religionId:c.faithId,stars,historicalRelevance:Math.max(1,stars*4+rng.int(-3,5)),impact:0,trait:rng.pick(TRAITS),achievement:'Their legacy is still being written.',active:true};s.people.push(p);addEvent(s,role==='General'?'military':role==='Religious Figure'?'religion':role==='Artist'?'culture':role==='Merchant'?'economy':'technology',`A remarkable ${role.toLowerCase()} emerges`,`${p.name}, a ${'★'.repeat(stars)} ${role.toLowerCase()}, has appeared in ${c.name}. Their talent may change the course of history.`,stars+3,[c.id],{personIds:[p.id]});return p}
export function createWorld(config:Partial<WorldConfig>={},seed=Date.now()):WorldState{
 const cfg:WorldConfig={mapSize:config.mapSize??'small',mapVariant:config.mapVariant??0,tribeCount:config.tribeCount??30,name:config.name??'New Chronicle'};const rng=new RNG(seed>>>0),{w,h}=dims(cfg.mapSize);const provinces:Province[]=[];
 for(let y=0;y<h;y++)for(let x=0;x<w;x++){const terrain=terrainAt(x,y,w,h,cfg.mapVariant,rng);const fertility=terrain==='plains'?rng.int(55,95):terrain==='forest'?rng.int(40,78):terrain==='ocean'?0:rng.int(10,48);provinces.push({id:y*w+x,x,y,terrain,fertility,ownerId:null,population:terrain==='ocean'?0:rng.int(40,260),cultureId:null,religionId:null})}
 const state:WorldState={seed,year:-3000,config:cfg,width:w,height:h,provinces,civilizations:[],religions:[],cultures:[],people:[],rulers:[],events:[],nextEventId:1,nextPersonId:1,nextReligionId:1,nextCultureId:1,nextCivilizationId:1,nextRulerId:1};
 const land=provinces.filter(p=>p.terrain!=='ocean');const count=Math.min(cfg.tribeCount,land.length);for(let i=0;i<count;i++){const available=land.filter(p=>p.ownerId===null&&neighbors(p,provinces).every(n=>n.ownerId===null));const home=rng.pick(available.length?available:land.filter(p=>p.ownerId===null));if(!home)break;let root=rng.pick(ROOTS);while(state.civilizations.some(c=>c.originTribe===root))root=`${rng.pick(ROOTS)}${rng.int(2,9)}`;const culture:Culture={id:state.nextCultureId++,name:`${root} Culture`,founded:state.year,population:home.population,color:COLORS[i%COLORS.length],provinces:1,heritage:[],originRealmId:state.nextCivilizationId};state.cultures.push(culture);const civ:Civilization={id:state.nextCivilizationId++,name:`${root} Tribe`,adjective:adjective(root),color:COLORS[i%COLORS.length],rank:'Tribe',founded:state.year,originTribe:root,capital:`${root} Camp`,cultureId:culture.id,rulerId:0,population:home.population,gdp:rng.int(8,20),military:rng.int(12,30),armySize:rng.int(40,150),technology:rng.int(2,12),stability:rng.int(45,85),prestige:rng.int(4,18),faithId:null,allies:[],rivals:[],provinces:[home.id],history:[],nameHistory:[{name:`${root} Tribe`,rank:'Tribe',from:state.year,reason:'founded by wandering clans'}],absorbedCultures:[],predecessorIds:[],peakPopulation:home.population,peakProvinces:1,warsWon:0,warsLost:0};home.ownerId=civ.id;home.cultureId=culture.id;state.civilizations.push(civ);newRuler(state,civ,rng)}return state;
}
function simulateYear(s:WorldState,rng:RNG){s.year++;const living=s.civilizations.filter(c=>c.provinces.length);for(const c of living){const ruler=s.rulers.find(r=>r.id===c.rulerId)!;const active=s.people.filter(p=>p.active&&p.realmId===c.id);let admin=ruler?.administration??50,mil=ruler?.military??50,dip=ruler?.diplomacy??50;
 c.population=Math.max(100,Math.round(c.population*(1+.008+c.stability/18000)));c.gdp=Math.max(1,c.gdp+(c.population/10000)*(0.5+admin/100)+active.filter(p=>p.role==='Merchant').reduce((a,p)=>a+p.stars*.5,0));
 c.technology=Math.min(1000,c.technology+.08+admin/300+active.filter(p=>p.role==='Scientist'||p.role==='Engineer').reduce((a,p)=>a+p.stars*.08*(admin/70),0));c.armySize=Math.round(c.population*(.035+mil/4000));c.military=Math.min(1000,c.military+.04+mil/400);c.prestige=Math.min(100,c.prestige+.05);c.stability=Math.max(1,Math.min(100,c.stability+(admin-50)/600));
 active.forEach(p=>{p.impact+=p.stars*(.4+(p.role==='General'?mil:p.role==='Merchant'||p.role==='Scientist'||p.role==='Engineer'||p.role==='Artist'?admin:dip)/100);p.historicalRelevance=Math.min(100,Math.round(p.stars*4+p.impact/8));if(s.year-p.born>rng.int(55,88)){p.died=s.year;p.active=false;p.achievement=`Their lifetime influence reached ${Math.round(p.impact)} impact points.`;addEvent(s,'society',`${p.name} dies`,`${p.name}, the celebrated ${p.role.toLowerCase()} of ${c.name}, has died with a historical relevance of ${p.historicalRelevance}.`,Math.min(10,3+p.stars),[c.id],{personIds:[p.id]})}});
 if(rng.chance(.014)){const notable=spawnPerson(s,c,rng);if(notable.role==='Artist'&&notable.stars>=4){const culture=s.cultures.find(x=>x.id===c.cultureId);const work=`${rng.pick(['Epic','Temple','Chronicle','Statue','Song Cycle'])} of ${c.capital}`;culture?.heritage.push(work);notable.achievement=`Created the ${work}, strengthening ${culture?.name??'their culture'}.`;addEvent(s,'culture',`${work} is created`,`${notable.name} created the ${work} for ${c.name}. The masterpiece strengthened the cultural heritage of its people.`,7,[c.id],{personIds:[notable.id],cultureIds:[c.cultureId]})}}if(rng.chance(.018)){const old=ruler;if(old){old.reignEnd=s.year;old.endProvinces=c.provinces.length;old.endTechnology=c.technology;old.endGDP=c.gdp;old.endPopulation=c.population;old.historicalRelevance=Math.min(100,Math.round((Math.abs((old.endProvinces??0)-old.startProvinces)*5+Math.max(0,(old.endTechnology??0)-old.startTechnology)/4+Math.max(0,(old.endGDP??0)-old.startGDP)/5+(old.administration+old.military+old.diplomacy)/9)));}const nr=newRuler(s,c,rng);addEvent(s,'diplomacy',`${nr.name} takes power`,`${nr.name}, a ${nr.trait.toLowerCase()} ruler with ${nr.administration} administration, ${nr.military} military and ${nr.diplomacy} diplomacy, begins a new reign in ${c.name}.`,6,[c.id])}
 const border=c.provinces.flatMap(id=>neighbors(s.provinces[id],s.provinces)).filter(p=>p.terrain!=='ocean'&&p.ownerId===null);if(border.length&&rng.chance(.055)){const p=rng.pick(border);p.ownerId=c.id;p.cultureId=c.cultureId;p.religionId=c.faithId;c.provinces.push(p.id)}
 const nr=rankFor(c);if(nr!==c.rank&&rankWeight(nr)>rankWeight(c.rank)){const old=c.name;c.rank=nr;c.name=polityName(c,nr,rng);c.adjective=adjective(c.name);c.nameHistory.push({name:c.name,rank:nr,from:s.year,reason:'political consolidation and growth'});addEvent(s,'culture',`${old} becomes ${c.name}`,`${old} has evolved into the ${nr.toLowerCase()} of ${c.name}. Its ${c.originTribe} roots remain central to its identity.`,8,[c.id])}
 if(!c.faithId&&s.year>-2400&&rng.chance(.004)){const prophet=spawnPerson(s,c,rng,'Religious Figure');const rel:Religion={id:s.nextReligionId++,name:`${rootName(c.originTribe)} ${rng.pick(['Faith','Way','Church','Tradition'])}`,founderPersonId:prophet.id,founder:prophet.name,founded:s.year,followers:c.population,color:COLORS[(c.id+9)%COLORS.length],holySites:[c.capital],doctrine:rng.pick(['Harmony and learning','Sacred conquest','Ancestor reverence','Mercy and pilgrimage','Cosmic order'])};s.religions.push(rel);c.faithId=rel.id;prophet.religionId=rel.id;s.provinces.filter(p=>p.ownerId===c.id).forEach(p=>p.religionId=rel.id);addEvent(s,'religion',`${rel.name} is founded`,`${prophet.name} founded ${rel.name} in ${c.capital}. The new faith begins among the ${c.adjective} people.`,9,[c.id],{personIds:[prophet.id],religionIds:[rel.id]})}
 const owned=s.provinces.filter(p=>p.ownerId===c.id);const provincialPopulation=Math.max(1,Math.round(c.population/Math.max(1,owned.length)));owned.forEach(p=>{p.population=provincialPopulation;if(!p.cultureId)p.cultureId=c.cultureId;if(c.faithId&&!p.religionId)p.religionId=c.faithId});if(c.faithId&&rng.chance(.025)){const frontier=owned.flatMap(p=>neighbors(p,s.provinces)).filter(p=>p.terrain!=='ocean'&&p.religionId!==c.faithId);if(frontier.length){const target=rng.pick(frontier);target.religionId=c.faithId;const rel=s.religions.find(r=>r.id===c.faithId);if(rel)addEvent(s,'religion',`${rel.name} spreads`,`${rel.name} gained a foothold in a new province beyond the heartland of ${c.name}.`,5,[c.id],{religionIds:[rel.id]})}}c.peakPopulation=Math.max(c.peakPopulation,c.population);c.peakProvinces=Math.max(c.peakProvinces,c.provinces.length)}
 // wars
 if(living.length>1&&rng.chance(.10)){const a=rng.pick(living),targets=living.filter(b=>b.id!==a.id&&a.provinces.some(id=>neighbors(s.provinces[id],s.provinces).some(p=>p.ownerId===b.id)));if(targets.length){const b=rng.pick(targets),ag=a.military+a.armySize/100+(s.rulers.find(r=>r.id===a.rulerId)?.military??50),bg=b.military+b.armySize/100+(s.rulers.find(r=>r.id===b.rulerId)?.military??50),winner=rng.next()*(ag+bg)<ag?a:b,loser=winner.id===a.id?b:a;const lp=rng.pick(loser.provinces);loser.provinces=loser.provinces.filter(id=>id!==lp);winner.provinces.push(lp);s.provinces[lp].ownerId=winner.id;s.provinces[lp].cultureId=winner.cultureId;winner.warsWon++;loser.warsLost++;addEvent(s,'military',`${winner.name} defeats ${loser.name}`,`${winner.name} won a decisive campaign and seized one province from ${loser.name}.`,7,[winner.id,loser.id])}}
 s.cultures.forEach(c=>{const ps=s.provinces.filter(p=>p.cultureId===c.id);c.provinces=ps.length;c.population=ps.reduce((a,p)=>a+p.population,0)});s.religions.forEach(r=>r.followers=s.provinces.filter(p=>p.religionId===r.id).reduce((a,p)=>a+p.population,0));
}
export function advanceWorld(world:WorldState,years:number){const s=structuredClone(world);const rng=new RNG((s.seed+s.year*31+years*997)>>>0);for(let i=0;i<years;i++)simulateYear(s,rng);return s}
